<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="4.3">
<file name="mokoki-core/ios64Main/kotlin/com/javiersc/mokoki/internal/LoggerNames.kt">
	<error line="70" column="18" severity="warning" message="The caught exception is swallowed. The original exception could be lost." source="detekt.SwallowedException" />
	<error line="34" column="25" severity="warning" message="This expression contains a magic number. Consider defining it to a well named constant." source="detekt.MagicNumber" />
</file>
<file name="mokoki-core/androidMain/kotlin/com/javiersc/mokoki/internal/LoggerNames.kt">
	<error line="31" column="18" severity="warning" message="The caught exception is swallowed. The original exception could be lost." source="detekt.SwallowedException" />
</file>
</checkstyle>